### PR TITLE
Feature Adding pictures

### PR DESCRIPTION
**Pull request by ctrl-alt-d**
# Why

* They are a missing feature on app that is to show pictures on screen, at this point, only filename and some text data appears.
* Bug navigating with arrows on grid head was introduced on previous PR (by me).

# What

* This PR fixes bug "keyboard arrows key doesn't work on grid head" (head had a wrong `onkeydown` attribute)
* On this PR a 100x100 pixels picture is showed on grid for each image file.
* I did a bit of refactor in some modules to make "easier" to write new functionalities.

Screenshot of app running

# How

* I tried to reference local pictures on `img` tag unsuccessfully. As a workaround I load picture from disk, I resize it with `SixLabors.ImageSharp` package and, instead to be saved to local disk, is showed as base64 image data.

# ToDo

* This is just the first version of adding pictures to grid. Some feature missing (as show picture in real size, add some css, etc)

# Also

* I wrote with VisualStudio Code. I guess it is changing tabs by spaces. This is an issue because is harder to check changes on github. Sorry.

### CODE REVIEW

**Comment by ctrl-alt-d** [comment]
# Changes

## Why

* Use base64 may cause DOM overloads.

## What

* New DI service `IPhotoReader` to server `img src` content to PhotoLabelerService

## How

* At this stage, `IPhotoReader`'s implemention ( `PhotoReaderBase64` ) still send `img src` as base64 data string. But, this is the first step before to create a controler ( MVC ) end point to serve local images and send the endpoint address instead base64 data.

**Comment by kastwey** [comment]
1. Regarding the dimensions of the image, I understand that by forcing it to be 100x100 pixels, the image will be distorted. Shouldn't we leave 100 pixels wide but let the length shorten in proportion?
2. Since PhotoLabeler also allows tagging videos, would it be possible to add the <video> tag instead of  when the file is a video? Currently, since no thumbnails are shown, if the video is the first element of a grid, the table never takes the focus, since the content is not rendered with the tabindex at 0.
3. Could you add an alt to each image that is equal to the photo tag, or in its absence, the name of the file?

Thanks a lot for all the work you are doing!

**Comment by ctrl-alt-d** [comment]
### About point 1 keeping aspect ratio:

Commit https://github.com/inclusive-thinking/photo-labeler/pull/4/commits/f7132366655c351bd968aafb60980f8b0debae6f fixes point 1:

>Regarding the dimensions of the image, I understand that by forcing it to be 100x100 pixels, the image will be distorted. Shouldn't we leave 100 pixels wide but let the length shorten in proportion?

Now picture is also 100x100 but instead of resizing with distorted now is resizing keeping aspect ratio and cropping center are:

```c#
var (x, y) = (image.Width, image.Height);
var minSide = Math.Min(x,y);
var (resizedX, resizedY) = (uiSize*x/minSide, uiSize*y/minSide);
var centerArea = new Rectangle( (resizedX-uiSize)/2, (resizedY-uiSize)/2, uiSize, uiSize);

image.Mutate(x => x
	.Resize(resizedX, resizedY)
	.Crop(centerArea)
	);
```
### About issues 2 (tagging videos) and 3 (img alt) from @kastwey comment 

Still in progress.

### About to show local files instead base64 data

* I started a +50 bounty on https://stackoverflow.com/questions/62741325/show-local-image-file-tmp-someimage-jpg
* I posted question on Electron Net project https://github.com/ElectronNET/Electron.NET/issues/449

**Comment by ctrl-alt-d** [comment]
Now all files (images and non images) have their own picture. For non images files they are and 'agnostic' file icon. For non-supported formats (video, tiff, ... ) a 'agnostic' picture or video icon is showed.

Fixed point 2 on @kastwey  https://github.com/inclusive-thinking/photo-labeler/pull/4#issuecomment-657959973 comments:

>Since PhotoLabeler also allows tagging videos, would it be possible to add the tag instead of  when the file is a video? Currently, since no thumbnails are shown, if the video is the first element of a grid, the table never takes the focus, since the content is not rendered with the tabindex at 0.

**Comment by ctrl-alt-d** [comment]
In commit #6e07733 added Alt to images as mentioned in https://github.com/inclusive-thinking/photo-labeler/pull/4#issuecomment-657959973:

>Could you add an alt to each image that is equal to the photo tag, or in its absence, the name of the file?

**Pull request merged**
